// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Book struct {
	ID            int32     `db:"id"`
	Title         string    `db:"title"`
	Author        string    `db:"author"`
	PublishedDate time.Time `db:"published_date"`
}
