// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
	"time"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, published_date) VALUES ($1, $2, $3) RETURNING id, title, author, published_date
`

type CreateBookParams struct {
	Title         string    `db:"title"`
	Author        string    `db:"author"`
	PublishedDate time.Time `db:"published_date"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Title, arg.Author, arg.PublishedDate)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedDate,
	)
	return i, err
}
